# Generated by Django 5.2.7 on 2025-11-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_like_rename_views_cout_paste_views_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='syntax',
        ),
    ]
