# Generated by Django 5.2.7 on 2025-11-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_paste_syntax'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='syntax',
            field=models.CharField(default='text', max_length=50, verbose_name='Синтаксис'),
        ),
    ]
